import { OwnerPhoto, TrustSections } from './trust-sections';
import { ArrowUpRight } from 'lucide-react';
export const dynamic = 'force-static';
const driveway='https://static.wixstatic.com/media/93329f34d0d44f7b8c3b2234ff583a8d.jpg';
const patio='https://images.squarespace-cdn.com/content/v1/66bacd1dbc31546179c30054/201433ff-9034-402f-b415-8587d27d3d20/5143218c3eb6640881dbab649599f155.jpg';
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<header><a className="brand" href="#">ethans<span>CONCRETE</span></a><nav aria-label="Main navigation"><a href="#work">The work</a><a href="#approach">The approach</a><a className="pill" href="#contact">Let’s talk <span><ArrowUpRight className="arrow-icon" aria-hidden="true" /></span></a></nav></header>
<main id="main"><div className="preview-notice">CONTENT PREVIEW — Sample reviews, project details, and service areas are clearly marked below.</div><section className="hero"><div className="hero-top"><p className="eyebrow">● &nbsp; INDEPENDENTLY CRAFTED IN ARKANSAS</p><p className="eyebrow side-note">SMALL JOBS. CONSIDERED DETAILS.</p></div><h1>Solid work.<br/><span>Quiet statement.</span></h1><div className="hero-bottom"><p>Patios, driveways, and the spaces in between.<br/>Thoughtfully poured. Personally finished.</p><a className="text-link" href="#work">Explore the possibilities <span>↓</span></a></div><figure className="hero-image"><img src={driveway} alt="Concrete driveway beside a timber garage and natural landscaping" fetchPriority="high"/><figcaption><span>BUILT FOR EVERYDAY LIVING</span><em>Concrete. In its element.</em></figcaption><span className="image-label">DESIGN INSPIRATION</span></figure></section>
<section className="intro reveal" id="approach"><div><p className="eyebrow">01 / A PERSONAL APPROACH</p><OwnerPhoto /></div><div><h2>One craftsman.<br/>Every detail.</h2><p>I’m Ethan. I run a one-man concrete business in Arkansas, focused on the small projects that make a home feel complete. When you reach out, you’re talking to the person doing the work.</p><p>From the first conversation to the final finish, it’s personal.</p></div></section>
<section className="work" id="work"><div className="section-heading reveal"><div><p className="eyebrow">02 / POSSIBILITIES IN CONCRETE</p><h2>Space to live.<br/>Made to last.</h2></div><p>A place to unwind. A better way home.<br/>Simple work, done with intention.</p></div><div className="project-grid"><article className="project reveal"><div className="project-photo"><img src={patio} alt="Clean concrete patio alongside a lawn and evergreen planting" loading="lazy"/><span>01</span></div><div className="project-caption"><h3>Room to slow down.</h3><span>PATIOS</span></div><p>Make a little more of your outdoors.</p><p className="project-sample">SAMPLE PROJECT · Conway · 240 sq ft patio</p><div className="before-placeholder">Before photo placeholder · real project pair coming soon</div></article><article className="project offset reveal"><div className="project-photo"><img src={driveway} alt="Concrete driveway framed by ornamental grasses" loading="lazy"/><span>02</span></div><div className="project-caption"><h3>A welcome home.</h3><span>DRIVEWAYS</span></div><p>A considered first impression, every day.</p><p className="project-sample">SAMPLE PROJECT · Little Rock · driveway refresh</p><div className="before-placeholder">Before photo placeholder · real project pair coming soon</div></article></div><div className="small-work reveal"><span className="eyebrow">AND THE SMALL THINGS</span><p>Walkways. Small slabs. A fresh start for that overlooked corner.</p><a className="text-link" href="mailto:ethan@ethansconcrete.com?subject=My%20concrete%20project">Tell me what you have in mind <span><ArrowUpRight className="arrow-icon" aria-hidden="true" /></span></a></div><p className="photo-credit">Design inspiration, not completed Ethans Concrete projects. Photography: <a href="https://www.brisbaneconcreter.com.au/brisbaneconcretedriveways" target="_blank" rel="noreferrer">Brisbane Concreter</a> & <a href="https://hvyconcreting.com.au/concrete-pathways" target="_blank" rel="noreferrer">HVY Concreting</a>.</p></section>
<TrustSections /><section className="contact reveal" id="contact"><p className="eyebrow">06 / LET’S MAKE SOMETHING SOLID</p><div className="contact-heading"><h2>Small project.<br/><span>Big difference.</span></h2><a className="round-arrow" href="mailto:ethan@ethansconcrete.com?subject=My%20concrete%20project" aria-label="Email Ethan about a project"><ArrowUpRight className="arrow-icon" aria-hidden="true" /></a></div><div className="contact-details"><p>Tell me about your space.<br/>We’ll take it from there.</p><a href="mailto:ethan@ethansconcrete.com">ethan@ethansconcrete.com</a><div className="phone-placeholder"><span>(501) 555-0142</span><small>Sample number · calling and texting unavailable</small></div></div></section></main><footer><a className="brand" href="#">ethans<span>CONCRETE</span></a><p>Arkansas soil. Solid foundations.</p><span>© 2026 Ethans Concrete</span></footer></>}


