import { UserRound, ArrowUpRight, Star } from 'lucide-react';

export function OwnerPhoto() {
  return <figure className="owner-placeholder"><UserRound size={48} strokeWidth={1} aria-hidden="true"/><figcaption>Ethan, owner & craftsman<span>Portrait placeholder · add a real photo</span></figcaption></figure>;
}

export function TrustSections() {
  return <>
    <section className="trust-section reviews reveal" id="reviews">
      <div className="section-heading"><div><p className="eyebrow">03 / WORD OF MOUTH</p><h2>Good work.<br/>Kind words.</h2></div><p className="sample-note">Sample testimonials for this preview.<br/>Names and experiences below are fictional.</p></div>
      <div className="review-grid">
        {[['Sarah M.', 'Patio · Conway', 'Ethan made our little backyard feel like a place we actually want to spend time. Clear communication and a really clean finish.'], ['James R.', 'Driveway repair · Little Rock', 'A small job, but it never felt like an afterthought. He talked through the plan and kept us informed along the way.'], ['Morgan T.', 'Walkway · Benton', 'We wanted something simple that suited the house. The finished walkway was exactly the look we had in mind.']].map(([name, job, quote]) => <article className="review" key={name}><span className="sample-tag">FICTIONAL SAMPLE</span><blockquote>“{quote}”</blockquote><p>{name}<span>{job}</span></p></article>)}
      </div>
      <div className="google-preview"><div><p className="eyebrow">GOOGLE REVIEWS · PREVIEW ONLY</p><div className="sample-rating"><strong>5.0</strong><span aria-label="Sample five-star rating">{Array.from({length:5},(_,i)=><Star key={i} size={16} fill="currentColor" aria-hidden="true"/>)}</span></div><p>Example rating · not an actual Google score.</p></div><div><button type="button" disabled title="Add the real Google Business Profile link to enable">Read reviews on Google <ArrowUpRight size={18}/></button><p>Google profile not connected yet.</p></div></div>
    </section>
    <section className="trust-section service-section reveal" id="services"><div className="section-heading"><div><p className="eyebrow">04 / SMALL WORK, DONE WELL</p><h2>A better corner<br/>of home.</h2></div><p>Patios, driveways, walkways, and small slabs.<br/>Tell me what you’re planning.</p></div><div className="service-details"><div><h3>Close to home.</h3><p className="sample-tag">EXAMPLE SERVICE AREA · TO CONFIRM</p><p>Little Rock · North Little Rock · Conway<br/>Benton · Bryant · Maumelle</p><p>Actual service towns and travel radius coming soon.</p></div><div><h3>The right size job.</h3><p className="sample-tag">SAMPLE JOB GUIDELINES</p><p>Patios around 150–400 sq ft, short walkways, small equipment slabs, and residential driveway work.</p><p>Minimum job size and pricing to be confirmed. Email your dimensions and town to discuss your project.</p></div></div></section>
    <section className="trust-section process reveal"><div className="section-heading"><div><p className="eyebrow">05 / FROM IDEA TO FINISH</p><h2>Simple steps.<br/>Solid results.</h2></div><p className="sample-note">Example process · final terms to be confirmed.</p></div><div className="process-grid">{[['01','Start a conversation','Email a few photos, rough dimensions, and your town. Tell me how you want to use the space.'],['02','Walk the space','A site visit helps establish access, preparation, drainage, and the finish you have in mind.'],['03','Agree on the details','Review a written scope and estimate, then agree on scheduling before work begins.'],['04','Make it solid','Preparation, pouring, finishing, and a final walkthrough—with care and curing guidance.']].map(([n,title,copy])=><article key={n}><span className="eyebrow">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="credentials"><p className="eyebrow">PEACE OF MIND</p><div><h3>Details you can check.</h3><p>Insurance documentation, applicable license information, and written warranty terms will appear here once verified.</p><span className="sample-tag">PLACEHOLDER · NO CREDENTIAL OR COVERAGE CLAIMS</span></div></div></section>
  </>;
}
